# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='house',
            field=models.IntegerField(verbose_name=1),
        ),
    ]
