# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 17:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20171027_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='house',
        ),
    ]
